import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/components/Providers';
import TopNav from '@/components/navbar/TopNav';
import { auth } from '@/auth';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next Match',
  description: 'Generated by create next app',
};

// 108 (Setting up a private channel)
// 151. Social Login part 2
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // <Providers/>でsession?.user?.idを使いたいけれども、client componentである<Providers/>ではsessionを取得できないので、
  // 親で尚且つsever componentの<RootLayout/>でsessionを取得して、子componentの<Providers/>にsession?.user?.idを渡します。
  const session = await auth();
  const userId = session?.user?.id || null;
  const profileComplete = session?.user.profileComplete as boolean;

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers userId={userId} profileComplete={profileComplete}>
          <TopNav />
          <main className={'container mx-auto'}>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
